os: linux
dist: xenial
language: node_js
node_js:
- node
services:
- docker
before_install:
- openssl aes-256-cbc -k $GCLOUD_FILE_SECRET -in gcloud_sa_key.json.enc -out gcloud_sa_key.json -d
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- gcloud auth activate-service-account --key-file=gcloud_sa_key.json
- gcloud auth configure-docker
- gcloud config set project $GCLOUD_PROJECT_ID
stages:
- Test
- Build
- Deploy
jobs:
  include:
  - stage: Test
    name: Run tests on the Angular Frontend
    script:
    - docker build -t eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest --build-arg env=$FRONTEND_ENVIRONMENT -f ./angular/Dockerfile.Test ./angular
    - docker push eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest
    - docker run --rm eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest npm run test:ci
