os: linux
dist: bionic
language: node_js
node_js:
- node
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_5cff05baf1ef_key -iv $encrypted_5cff05baf1ef_iv -in gcloud_sa_key.json.enc -out gcloud_sa_key.json -d
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- gcloud auth activate-service-account --key-file=gcloud_sa_key.json
- gcloud config set project $GCLOUD_PROJECT_ID
stages:
- Test
- Build
- Deploy
jobs:
  include:
  - stage: Test
    name: Run tests on the Angular Frontend
    script:
    - docker build -t $DOCKER_USERNAME/docker_frontend_dev --build-arg env=$FRONTEND_ENVIRONMENT
      -f ./angular/Dockerfile.Test ./angular
    - docker tag $DOCKER_USERNAME/docker_frontend_dev eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest
    - docker push eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest
    - docker run --rm eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest npm run test:ci
