sudo: required
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t $DOCKER_USERNAME/docker_frontend ./angular;
  - docker tag $DOCKER_USERNAME/docker_frontend registry.heroku.com/$HEROKU_APP_FRONTEND/web;
  - docker build -t $DOCKER_USERNAME/docker_backend ./nodejs-api;
  - docker tag $DOCKER_USERNAME/docker_backend registry.heroku.com/$HEROKU_APP_BACKEND/web;
  - docker build -t $DOCKER_USERNAME/docker_nginx ./nginx;
  - docker tag $DOCKER_USERNAME/docker_nginx registry.heroku.com/$HEROKU_APP_NGINX/web;

deploy:
    provider: script
    script: 
      # push to dockerhub & heroku 
      #docker push $DOCKER_USERNAME/docker_frontend;
      docker push registry.heroku.com/$HEROKU_APP_FRONTEND/web;
      heroku container:release web --app $HEROKU_APP_FRONTEND;
      #docker push $DOCKER_USERNAME/docker_backend;
      docker push registry.heroku.com/$HEROKU_APP_BACKEND/web;
      heroku container:release web --app $HEROKU_APP_BACKEND;
      #docker push $DOCKER_USERNAME/docker_nginx;
      docker push registry.heroku.com/$HEROKU_APP_NGINX/web;
      heroku container:release web --app $HEROKU_APP_NGINX;
    on: 
      branch: master