sudo: required
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t $DOCKER_USERNAME/docker_frontend ./angular;
  - docker build -t $DOCKER_USERNAME/docker_backend ./nodejs-api;
  - docker build -t $DOCKER_USERNAME/docker_nginx ./nginx;