sudo: required
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

stages:
  - build
  - tag
  - deploy
  
jobs:
  include:
    - stage: build               
      name: "Build Docker images"           
      script: 
        - docker build -t $DOCKER_USERNAME/docker_frontend ./angular
        - docker build -t $DOCKER_USERNAME/docker_backend ./nodejs-api
        - docker build -t $DOCKER_USERNAME/docker_nginx ./nginx