os: linux
dist: bionic
language: node_js
node_js:
- node
services:
- docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -k "$GCLOUD_SA_KEY" -in gcloud_sa_key.json.enc -out gcloud_sa_key.json -d
# - docker login -u _json_key --password-stdin https://eu.gcr.io < gcloud_sa_key.json
- gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT --key-file=gcloud_sa_key.json
- gcloud auth configure-docker
- gcloud config set project "${GCLOUD_PROJECT_ID}"
stages:
- Test
- Build
- Deploy
jobs:
  include:
  # - stage: Test
  #   name: Run tests on the Angular Frontend
  #   script:
  #   - docker build -t $DOCKER_USERNAME/docker_frontend_dev --build-arg env=$FRONTEND_ENVIRONMENT -f ./angular/Dockerfile.Test ./angular
  #   - docker tag $DOCKER_USERNAME/docker_frontend_dev eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest
  #   - docker push eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest
  #   - docker run --rm eu.gcr.io/$GCLOUD_PROJECT_ID/angulartest npm run test:ci
  - stage: Build               
    name: "Build Angular Frontend Docker image"           
    script: 
      - docker build -t $DOCKER_USERNAME/docker_frontend --build-arg env=$FRONTEND_ENVIRONMENT ./angular
      - docker tag $DOCKER_USERNAME/docker_frontend eu.gcr.io/$GCLOUD_PROJECT_ID/$GCLOUD_ANGULARSERVICE
      - docker push eu.gcr.io/$GCLOUD_PROJECT_ID/$GCLOUD_ANGULARSERVICE
      - gcloud run deploy $ANGULARSERVICE --platform=managed --region=europe-west1 --allow-unauthenticated --image=eu.gcr.io/$GCLOUD_PROJECT_ID/$ANGULARSERVICE
