steps:
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/angulartest", "-f", "./angular/Dockerfile.Test", "./angular"]

    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "eu.gcr.io/$PROJECT_ID/angulartest"]

    - name: "gcr.io/cloud-builders/docker"
      id: testangular
      args: ["run", "--rm", "eu.gcr.io/$PROJECT_ID/angulartest", "npm", "run", "test:ci"]

    - name: "gcr.io/cloud-builders/docker"
      id: buildangular
      waitFor: ["testangular"]
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE", "--build-arg", "env=production", "-f", "./angular/Dockerfile.Gcloud", "./angular"]

    - name: "gcr.io/cloud-builders/docker"
      id: buildapi
      waitFor: ["testangular"]
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/$_NODESERVICE", "./nodejs-api"]
  
    - name: "gcr.io/cloud-builders/docker"
      id: pushangular
      waitFor:
        - buildangular
      args: ["push", "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]

    - name: "gcr.io/cloud-builders/docker"
      id: pushnodeapi
      waitFor:
        - buildapi
      args: ["push", "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"]
  
    - name: "gcr.io/cloud-builders/gcloud"
      id: deployangular
      waitFor: 
        - pushangular
      args: ["run", "deploy", "$_ANGULARSERVICE",
             "--platform", "managed", "--region", "europe-west1",
             "--allow-unauthenticated",
             "--image",  "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]

    - name: "gcr.io/cloud-builders/gcloud"
      id: deploynodeapi
      waitFor:
        - pushnodeapi
      args: ["run", "deploy", "$_NODESERVICE",
             "--platform", "managed", "--region", "europe-west1",
             "--allow-unauthenticated",
             "--image",  "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"]
             
    # - name: "gcr.io/cloud-builders/gcloud"
    #   args: ["run", "services", "update-traffic", "$_ANGULARSERVICE", "--to-latest", "--platform", "managed", "--region", "europe-west1"]

images:
    - "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"
    - "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"