steps:
    - name: "gcr.io/cloud-builders/docker"
      id: buildtest_image
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/angulartest", "-f", "./angular/Dockerfile.Test", "./angular"]

    - name: "gcr.io/cloud-builders/docker"
      id: pushtest_image
      args: ["push", "eu.gcr.io/$PROJECT_ID/angulartest"]

    - name: "gcr.io/cloud-builders/docker"
      id: test_angular
      args: ["run", "--rm", "eu.gcr.io/$PROJECT_ID/angulartest", "npm", "run", "test:ci"]

    - name: "gcr.io/cloud-builders/docker"
      id: build_angular
      waitFor: ["test_angular"]
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE", "--build-arg", "env=production", "-f", "./angular/Dockerfile.Gcloud", "./angular"]

    - name: "gcr.io/cloud-builders/docker"
      id: build_api
      waitFor: ["test_angular"]
      args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/$_NODESERVICE", "./nodejs-api"]
  
    - name: "gcr.io/cloud-builders/docker"
      id: push_angular
      waitFor:
        - build_angular
      args: ["push", "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]

    - name: "gcr.io/cloud-builders/docker"
      id: push_nodeapi
      waitFor:
        - build_api
      args: ["push", "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"]
  
    - name: "gcr.io/cloud-builders/gcloud"
      id: deploy_angular
      waitFor: 
        - push_angular
      args: ["run", "deploy", "$_ANGULARSERVICE",
             "--platform", "managed", "--region", "europe-west1",
             "--allow-unauthenticated",
             "--image",  "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]

    - name: "gcr.io/cloud-builders/gcloud"
      id: deploy_nodeapi
      waitFor:
        - push_nodeapi
      args: ["run", "deploy", "$_NODESERVICE",
             "--platform", "managed", "--region", "europe-west1",
             "--allow-unauthenticated",
             "--image",  "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"]
             
    # - name: "gcr.io/cloud-builders/gcloud"
    #   args: ["run", "services", "update-traffic", "$_ANGULARSERVICE", "--to-latest", "--platform", "managed", "--region", "europe-west1"]

images:
    - "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"
    - "eu.gcr.io/$PROJECT_ID/$_NODESERVICE"