steps:
    - name: "eu.gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/$_ANGULARSERVICE", "--build-args", "env=production", "./angular"]
  
    - name: "eu.gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]
  
    - name: "eu.gcr.io/cloud-builders/gcloud"
      args: ["run", "deploy", "$_ANGULARSERVICE",
             "--platform", "managed", "--region", "europe-west1",
             "--allow-unauthenticated",
             "--image",  "gcr.io/$PROJECT_ID/$_ANGULARSERVICE"]

images:
    - "eu.gcr.io/$PROJECT_ID/$_ANGULARSERVICE"