version: "3.8"
services:
  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile.Dev
    volumes:
      - /app/node_modules
      - ./angular:/app
  api:
    build:
      context: ./nodejs-api
      dockerfile: Dockerfile.Dev
    volumes:
      - /app/node_modules
      - ./nodejs-api:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.Dev
      context: ./nginx
    depends_on:
      - frontend
      - api
    ports:
      - 4712:80
