FROM node:current-stretch-slim
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY . .

RUN apt-get update && apt-get install -y --no-install-recommends chromium
ENV CHROME_BIN=chromium

CMD ["npm", "run", "start_docker"]
